const OET_WORD_LIST = [
    "Building sites",
  "Blotches",
  "Scalp",
  "Swelling",
  "Eczema",
  "Itchy",
  "Burning",
  "Constipation",
  "Heel",
  "Osteoarthritis",
  "Atrial fibrillation",
  "Translator",
  "Bruising",
  "Sway",
  "Disorientation",
  "Emotional outbursts",
  "Choking",
  "Autism",
  "Holter monitor",
  "Muscle biopsy",
  "Blood thinners",
  "Unsaturated fats",
  "Dizzy spells",
  "Palpitations",
  "Breathless",
  "Bereavement",
  "Dancing instructor",
  "Died",
  "Ear infection",
  "Ablation",
  "Flu",
  "Alzheimer's disease",
  "Rods",
  "Jump",
  "Vitamin D",
  "Sleep apnoea",
  "Shoulders",
  "Fatigue",
  "Anxious",
  "Journalist",
  "Numbness",
  "Goalkeeper",
  "Tea",
  "Irritable bowel syndrome",
  "Chef",
  "Insomnia",
  "Tomatoes",
  "Lying down",
  "Antihistamines",
  "Central nervous system",
  "Compartment syndrome",
  "Carpenter",
  "Tingling",
  "Stiffness",
  "Collarbone",
  "Acupuncture",
  "Left calf",
  "Varicose veins",
  "Wrist brace",
  "Metal rod",
  "Bent", "Strawberry tongue", "Irritable", "Washing hair", "Sepsis", "Pneumonia",
  "Diabetes", "Knife and fork", "Scarlet fever", "Bloodshot", "Fingertips",
  "Cracked lips", "Japan", "Epilepsy", "Concentrate", "Booster injection",
  "Febrile convulsion", "Pressure sores", "Physiotherapy", "Events manager",
  "Sticky", "Change dressing", "Chubby", "Judge distance", "Multiple sclerosis",
  "Administrator", "Preventer", "Steroid", "Menstruation", "Car accident",
  "Fuzzy", "Injection", "Lunch time", "Hearing loss", "Swallow", "Vocabulary",
  "Vascular", "Eating", "Some sort of food", "Urinalysis", "Deafness",
  "Magazine editor", "Lethargic", "Visual perception", "Heartbeats", "Tightness",
  "Financial problems", "Cut two fingers", "Nausea", "Lung expansion", "Tantrum",
  "Groin area", "Asking", "Nausea", "Indigestion", "Full blood count", "Cloudy", "Cold compress",
  "Lethargic", "Confidence", "Popping", "Clicking", "Heel", "Osteoarthritis", "Deep vein thrombosis",
  "Atrial fibrillation", "Swollen", "Yoga", "Aerobic exercises", "Physiotherapy session", "Calf calves", "Crutches", "Translator", "Mouth ulcers", "Infection", "Compartment syndrome",
  "Painkillers", "Antisocial", "Chills", "Fingertips", "B12 deficiency", "Angina", "Rib cage", "Ribcage", "Swallowing", "Drained", "Confusion",
  "Shivering", "Stinging", "Bloating", "Tonsillectomy", "Potassium level", "Overactive thyroid",
  "Gymnastics", "Anaemia", "Indoor exercises", "Tongue-tie", "Crusty mucus",
  "Dyspepsia", "Crowded places", "White crusts", "Antihistamine", "Breathless", "Infertile", "Night sweats", "Sticky", "Strangulation", "Lying flat", "Surveyor", "Clockwise", "Left calf", "Punctured lung",
  "Social gatherings", "Tinnitus", "Vomited", "Injection", "Hearing loss", "Stomach", "Groin",
  "Gastric bypass", "Angina", "Confidence", "In concentration", "Baggage", "Tailor", "Tendon",
  "Savoury snacks", "Nasal spray", "Thighs", "Programmer", "Itchy", "Red meat", "Shower gels",
  "Darker", "Herbal oil", "Obese", "Bladder", "Hiking", "Calamine lotion", "Tonsillitis", "Dragging",
  "Corticosteroids", "Spider", "Thirsty", "Greasy", "Whooping cough", "Scrotum", "Whiplash injury",
  "Pituitary", "Pleurisy", "Disorientation", "Construction worker", "Pulsing", "Bruise", "Red spots",
  "Dry mouth", "Distracted", "Ginseng supplements", "Senna tablets", "Neighbour", "Incontinence",
  "Burping", "Sales manager", "Pre-eclampsia", "Four months", "Meat", "Oranges", "Lemonades",
  "Smoking", "Bereavement", "Vegetarian", "Intermittent", "Vocabulary", "Blurred", "Financial difficulties", "Graphic designer", "Driving", "Down syndrome", "Motivation", "Sinusitis", "Temper",
  "Mononucleosis", "Swollen ankle", "Asthma", "Engineer", "Mumps", "Sleepiness", "Magnesium tablets", "Magnesium", "Potassium", "Sodium", "Garlic", "Widow", "Building inspector", "Pneumonia", "Amnesia", "Incontinence", "Testosterone", "Botanist", "Lupus", "Left tibia", "Steroids", "Infertile", "Stinging", "Headache", "Knife", "Knives", "Shoulders", "Handwriting",
  "Low fat", "Low-fat diet", "Gallstones", "Gallbladder", "Burning", "Dragging", "Self-catheterization",
  "Zika virus", "Clumps", "Overactive thyroid", "Irritated", "IV antibiotics", "Specialised message",
  "Compression socks", "Swelling up", "Fever", "Heavy lifting", "Liposuction", "Croup", "Carpenter",
  "Fell", "Steady", "Glue ear", "Agitated", "Ammonia", "Vomiting", "Central nervous system", "Swelling", "Malarone tablets", "Administrator", "Broken ribs", "Heartbeat", "Anger",
  "Swollen tongue", "Pneumonia", "Eczema", "Multiple sclerosis", "Booster injection", "Sticky",
  "Cracked lips", "Strawberry tongue", "Febrile convulsion", "Epilepsy", "Irritable", "Fingertips",
  "Bloodshot", "Groin area", "Scarlet fever", "Judge distance", "Itchy", "Eczema", "Programmer", "Red meat", "Calamine lotion", "Perfumes",
  "Pink eye", "Angina", "Shivering", "Gastric bypass", "Bump his head", "Bumps", "Memory", "Tonic-clonic", "Partial seizure", "Tingling", "Paracetamol", "Beta blocker", "Concussion", "Glandular fever", "Lupus", "Pulmonary embolism", "Joints pain", "VNS therapy", "Many strokes", "Freeze",
  "Dribbling", "Convulsions", "Blood clots", "Financial advisor", "Frontal lobe", "Seizures",
  "Meniere's disease", "Preventer", "Fuzzy", "Loss of hearing", "Social gathering", "Propranolol", "Tetanus", "Tinnitus", "Mouth ulcer", "Canker sores", "16mg",
  "Vision", "Lunchtime", "Squat position", "Acute inflammation", "Anti-clockwise", "Crackling",
  "Patella", "Fuzzy", "Vomited", "Exercise straps", "Hearing loss", "Hamstring", "Stretching", "Urgency",
  "Crackling", "Knee", "Diabetes", "Chef", "Intense", "Irritable bowel syndrome", "Femur", "Pins and needles", "Antihistamine", "Swelling", "Cold sores", "Depression", "Heart murmur", "Cycling", "Iron deficiency anaemia", "Nightmares", "Lower back", "Heat pads", "Engineering", "Lying flat position", "Vomiting", "PPI (proton pump inhibitors)", "Dyspepsia", "Strangulation", "Kidney infection", "Wheezing", "Sweating", "Pleurisy", "Jabbing", "Counselling", "Tennis ball", "Sleep apnoea", "Spasm", "Breathlessness", "Ibuprofen", "Pneumonia", "Bloating", "Shivering", "Perfume", "White crust", "Greasy", "Sticky", "Night sweats", "Crowded places", "Surveyor", "Angina",
  "Infertile", "Confidence", "Antisocial", "Pink eyes", "Gastric bypass surgery", "Swallowing",
  "Shivering", "Lethargic", "Cold compression", "Above normal", "Dread", "B12 deficiency", "Chef",
  "Firefighter", "Heartburn", "Bloating", "Anxiety", "Tired", "Weightlifter", "Allergy test", "Dementia",
  "Training", "Swimming", "Soccer", "Alcohol", "Fibromyalgia", "Antispasmodic", "Disc prolapse",
  "Cracked", "Pancreatitis", "Antifungal", "Mechanic", "Vomiting", "Sinus infection", "Ladder",
  "Rotator cuff", "Co-codamol", "Ice packs", "Bump on the head", "Bumps", "Complex partial",
  "Trance", "Dribble", "Freeze", "VNS therapy", "Convulsions", "Weight", "Ribs", "Pulmonary embolism", "Heparin injections", "Skin rashes", "Lupus", "Joint pain", "Stroke", "Vertigo",
  "Concussions", "Anti-inflammatory", "Corticosteroid injection", "Ethanol", "Carbohydrates",
  "Golf", "Constipation", "Depression", "Neck", "Thyroid", "Steroid injection", "3 miscarriages", "C-reactive protein", "Ultrasound", "Arthritis", "Uterine cancer", "Uterine balloon", "Right shoulder", "Financial advisor", "Juvenile rheumatic arthritis", "Lupus",
  "Light bleeding", "Menopause", "Eczema", "Meningitis", "Environmental engineering", "Scalp",
  "Saline drip", "Hand cream", "Ointment", "Kidney stone", "Insomnia", "Freeze", "Ribs", "Pulmonary embolism", "Heparin injections", "Skin rashes", "Lupus", "Joint pain", "Stroke", "Vertigo", "Bloating",
  "Anxiety", "Tired", "Swimming", "Soccer", "Alcohol", "Stiff", "Bloated", "Debilitating", "Journalist",
  "Colonoscopy", "Multivitamin", "Vitamin B12", "Swimming", "Gastric flu", "Fitful", "Fatigue", "Cloudy",
  "Palpitations", "Barium enema", "Stomach ulcer", "Trembling", "Law", "Isolated", "Clouded", "Joint pain", "Metallic", "Caffeine", "Cystoscopy", "High blood pressure", "Itching", "IBS", "Transplant", "Dark red", "Protein", "Big toe", "Joints", "Wrists", "Shingles", "Anti-inflammatory", "Cut my food", "Concentration", "Physical activity", "Graded exercise therapy", "Counsellor", "Faint", "Palpitations", "Sweating", "Sensitivity to light", "Underactive thyroid", "Contagious", "Antiseptic shampoo", "Irritated skin", "Dilantin", "Rhinocort nasal spray", "Mucofen", "Flurbiprofen", "Klonopin", "Rivaroxaban", "Mitomycin", "Flomax", "Advair diskus", "Celebrex", "Neurontin", "Cyclophosphamide", "Allopurinol", "Morphine", "Zolpidem", "Nitroglycerin", "Clopidogrel", "Keflex", "Atenolol", "Sodium bicarbonate", "Neoprene", "Cardizem", "Metoprolol", "Hydralazine", "Labetalol", "Levothyroxine", "Zyrtec", "Proscar", "Synthroid", "Motrin", "Avelox", "Codeine", "Chlordiazepoxide", "Clidinium", "Simvastatin", "Flagyl", "Daptomycin", "Primaxin", "Methadone", "Levaquin", "Floppy", "Tongue", "Earache", "Spasms", "Gums", "Exhaustion", "Breast cancer", "Femur", "Hay fever", "Project manager", "Patches", "Antacid", "Craving", "Irritable", "Pus", "Hard", "Lighter", "New mouse", "Golf ball", "Collarbone", "Restless legs syndrome", "Carpal tunnel syndrome", "Scar", "Aspiration", "Burning", "Yoga", "Fish oil", "Nausea", "Zinc", "Humidity", "Stiffness", "Pregnancy", "Clicking", "Gardener", "Fracture", "Breathless", "Cheese", "Drill", "Mood swing", "Constant pain", "Gardener", "Fracture", "Breathless", "Cricking", "Burning", "New mouse", "Jewellery maker", "Scar", "Aspiration", "Burning sensation", "Prostate cancer", "Echocardiogram", "Fluid", "Salads", "Dialysis", "Life-threatening", "Finances", "Cycling", "Itchy leg", "Dark red urine", "Cystoscopy", "Nosebleeds", "Verapamil", "Vegetarian diet", "Vegan", "Dietary", "Dietitian", "Tooth extraction", "Cauterisation", "Cardiologist", "Dry cough", "Respiratory infection", "Depression", "Biopsy", "Laparoscopy", "Swallowing", "Graphic designer", "Blood test", "Memory lapse", "Fidget", "Strengthening exercises", "Cellulitis", "Stumbling", "Aneurysm", "Sides of buttocks", "Seizure", "Soccer", "Dairy", "Diary", "Physiotherapy", "Balance", "Bearable", "Beer", "Bear", "Bank manager", "Liver", "Cancer", "Tired", "Eyes", "Migraines", "Acupuncture", "Blotches", "Alcohol", "Firefighters", "Migraine", "Gluten", "ACE inhibitors", "Stroke", "Cracked", "Bloating", "Brown marks", "Rheumatology", "Big toe arthritis", "Baclofen", "Magazine editor", "High-impact sports", "Sugar", "Swelling", "Constipation", "Darker", "Frightening", "Vibrating", "Carpenter", "Restricted diet", "Gout", "Acupuncture", "Dermatology consultation", "Corticosteroids", "Allergy", "Pruritus", "Hives", "Orange", "Lemonade", "Sales manager", "Sepsis", "Multiple organ failure", "Peritonitis", "Right thumb", "Steroid", "Stomach pain", "Hernia", "Sepsis", "Ventilation", "Colonoscopy", "Stoma", "Cholesterol", "Meningitis", "Right thumb", "Menopause", "Growing pain", "Arthritis", "Flat mattress", "Coma", "Hernia", "Sepsis", "Ventilator", "Abdominal pain", "Tonsillitis", "Tonsil", "Tonsillectomy", "Withdrawn", "Knee", "Limping", "Limb", "Shoulder", "Ankles", "Stinging", "Healthy", "Gall stones", "Tingling", "Muscles", "Back", "Incontinence", "Accountant", "Sister", "Drive", "Aerobics", "Sugar", "Healthy", "Low-fat diet", "Cold water", "Swimming", "Flight attendant", "Blood transfusion", "Perfumed", "Hydrated", "Emotional", "Beer", "Skin is dry and flaky", "Diet free of gluten", "Blisters", "Eczema", "Asthma", "Bicycle", "Basketball", "Oily fish", "Flight attendant", "Depression", "Throat infection", "Perfumed", "Ketogenic",
  "Cataract", "Blood transfusion", "Left thumb", "Flaky", "Drinking tea", "Water", "Drooping eyelid",
  "Peanut", "Active thyroid", "Security guard", "Bloating", "Tingling", "Nephrologist", "Neurologist", "High-fibre diet", "Accountant", "Cycling", "Kidney cancer", "Sciatica", "Physiotherapy", "Hiking", "Eczema", "Kidney graft", "Security guard", "Canal", "Calves", "Thighs", "Two toes", "Abdomen", "Warehouse", "Pus", "Stinging", "Piercing", "Headache", "Botox", "Wheezing", "Fatigue", "Heartburn", "Angina", "Chest", "Anaemia", "Shoulder", "Badminton", "Blotchy", "Leathery skin", "Gout", "Hips", "Stiff", "Weakness", "Pins and needles", "Energy", "Ice packs", "Basketball", "Left thigh", "Longstanding", "Swollen", "Dark red", "Eczema", "Bandage", "Stiff", "Weakness", "Swollen", "Panic attack", "Hypertension", "Eczema", "Herbalist", "Guitar", "Hydrocortisone", "Dark red", "Smell", "Ice packs", "Weightlifting", "Alcohol", "Chest infection", "Obesity", "Left ventricle", "Stage 3", "Call centre", "Convenience diet", "Scuba diving", "Vascular dementia", "Leukaemia", "Swimming", "Fractured rib", "Ears", "Sinuses", "Management", "Scoliosis", "Translator", "Fertility", "Breastfeeding", "Blurred vision", "Stroke", "Angina", "Knees", "Absence seizures", "Rheumatoid fever", "Echo", "Stuttered", "Acoustic neuroma", "Omega-3", "Hacking", "Whispering", "Dog trainer", "Asthma", "Lupus groin", "Hammer", "Incontinence", "Web designer", "Pleurisy", "Chest tightness", "Chest infection", "Translator", "Fertility", "Stutter", "Dog trainer", "Jogging", "Hacking", "Rheumatic fever", "Left leg", "Angina", "Obesity", "Blurring of vision", "Fast food", "Vascular dementia", "Stroke", "Swimming", "Voice", "Breastfeeding", "Fractured rib", "Knee", "Ears", "Scoliosis", "Astigmatism", "White", "Glue", "Oral antibiotics", "Mushrooms", "Sour taste", "Sore throat", "Choking", "Osteoarthritis", "Warm compresses", "Dental assistant", "Rubella", "Salmonella", "Styes", "Melatonin", "Melanoma", "Tea tree oil", "Topical antibiotic", "Blinking", "Dandruff", "Regurgitation", "Computer", "Meniere's disease", "Lunch", "Social gathering", "Tinnitus", "Stretching", "Acute inflammation", "Injections", "Bracing", "Shoulders", "Jaundice", "June", "Muscle relaxant", "Thighs", "Prickling", "Knee replacement", "Humid", "Clumsy", "Dark", "Hepatitis", "Tai chi", "Refreshed", "Aching", "Bilirubin", "Dreadful fatigue", "Cirrhosis", "Constipation", "Prostate cancer", "Dehydrated", "Stabbing", "Restless at school", "Tomatoes", "Ointment", "Clumsy", "Brain fog", "Dizziness", "Handshake", "Dark urine", "Tendon", "Big toe", "Slurred", "Continence", "Neighbours", "Driving", "Savoury", "Weight", "Diarrhoea", "Baggage handler", "Luggage", "Tired", "Vitiligo", "Vertigo", "Commercial artist", "Strength", "Laxatives", "Cycling", "Junk food", "Climbing stairs", "Jaw exercise", "Underactive thyroid", "Swelling", "Uric acid", "Osteoporosis", "Big toe", "Software designer", "Lifting weights", "Calcium", "Constipation", "Preventive measures", "Femur", "Irritable bowel syndrome", "Ulcerative colitis", "Gastric reflux", "Menopause", "Cholesterol", "Sprain", "Colonoscopy", "Pressure", "Constipation", "Glandular fever", "Sweating", "Sepsis", "Dental hygienist", "Jaundice", "Blood thinners", "Insomnia", "Bitter taste", "Gallstone", "Discolouration", "Sodium", "Magnesium", "Potassium", "Burning", "Environmental engineer", "Stiff", "Hand cream", "Itching", "Eczema", "Sprained ankle", "Scalp", "Panic attack", "Swollen", "Dressing", "Pressure", "Temperature", "Tetanus vaccination", "Sepsis", "Financial difficulties", "Difficult",
  "Different", "Deficiency", "Depression", "Deafness", "Awareness", "Brain fog", "Sharp mind",
  "Bereavement", "Surgery", "Osteomyelitis", "Stroke", "Vascular", "Nail", "Opioids", "Stiffness",
  "Fainting", "Pelvic ultrasound", "Cramps", "Clots", "Child care assistant", "Retirement", "Dancing",
  "Cranberry supplement", "Blurring", "Energy", "Dizzy", "Lower back", "Ice packs", "Nausea", "Ankle",
  "Hopelessness", "Lethargic", "Tingling", "Ovarian cysts", "Tingling sensation", "Rubbing ointment",
  "Tiger balm", "Unsteady", "Blurred vision", "Paracetamol", "Shoulder", "Badminton", "Blotchy", "Jet lag", "Wrists", "Toe", "Tarsal fracture", "Hips", "Joints", "Ribs", "Gout", "Clammy", "Chest pain",
  "Calves", "Throat cancer", "Ginseng", "Botox", "Lethargy", "Warehouse", "Triptan", "Stiff", "Weakness",
  "Guitar", "Basketball", "Imbalance", "Prediabetes", "Heavy", "Weightlifting", "Pins and needles",
  "Energy", "Ferritin", "Amino acid", "Panic attack", "Dandruff", "Bold patches", "Anxiety attacks",
  "Growing pain", "Hotel receptionist", "Poliovirus", "Thyroid function test", "Hormonal imbalance",
  "Bald patches", "Scabbing", "Scabies", "Beta blockers", "Acoustic neuroma", "Stuttered", "Right knee", "Bunion", "Crutches", "Hammer", "Type 1 diabetes", "Web designer", "Freelancer journalist",
  "Distorted", "Stationary life", "DM", "Trapped nerve", "Incontinence", "Gout", "Sedentary life",
  "Omega-3", "Hip", "Grain", "Tongue", "Crutches", "Hammer", "Tongue", "Lump", "Right knee", "Blurred vision", "Stutter", "Vegetarian", "Big toes", "Sleep apnoea", "Kidney disease", "Chiropractor",
  "Graphic designer", "Swimming", "Rash", "Bending over", "Dairy products", "Ears", "Osteoarthritis",
  "Intense burning", "Breastfeeding", "A translator", "Voice", "Knees", "Scoliosis", "Fertility", "Absence seizures", "Fractured rib", "Balance", "Playing squash", "Whiplash", "Mouse", "Acupuncture", "An accountant", "Appendicitis", "Dandruff", "An underactive thyroid", "Depression", "Gout", "Pelvic congestion", "Chest pain", "Mild fever", "Bone loss in jaw", "A web designer", "Canker sores",
  "Lupus", "Epilepticus", "Whipple's disease", "Gastroenterology", "Involuntary", "Tonic-clonic",
  "Pepper", "Peppermint", "Cricket", "Tremor", "Uncomplicated pregnancy", "Reflexes", "Imitating",
  "Breakfast", "Rely on", "Exacerbate", "Housewife", "Neighbour", "Work", "Patchy", "Jaundice",
  "Hepatitis", "Steroid cream", "Cirrhosis", "Inflammatory", "Inflammation", "Inflamed", "Exercise",
  "Stress", "Constipation", "Brain fog", "Swallowing", "Vegan", "Prostate cancer", "Constipation",
  "Dark", "Bilirubin", "Uterine cancer", "Big toe", "Light", "Regular", "Ultrasound", "Osteoporosis",
  "Arthritis", "Uterine balloon therapy", "Preventative medicine", "Miscarriages", "High-impact sport", "Sciatica", "Uric acid", "A sprain", "Femur", "Laser", "Constipation", "Traumatic", "Bad haemorrhage", "Bend it", "Brownish", "Financial advisor", "Breastfeeding", "An ultrasound", "Bent",
  "Software designer", "Vomiting", "Appetite", "Cholesterol", "Calcium", "Menopause", "Shockwave surgery", "Colonoscopy", "Ulcerative colitis", "Reflux", "Boxing", "Grain", "Financial advisor",
  "Homemaker", "Osteoporosis", "Arthritis", "Constipation", "Regular", "Brownish", "Dull ache",
  "Food poisoning", "Software designer", "Anxiety", "Gastric reflux", "Workaholic", "Electric", "Shock",
  "Menopause", "Irritable bowel syndrome", "Calcium", "Cholesterol", "Seafood", "Grain", "Nausea",
  "Shower gel", "Itchy", "Fatigue", "Deodorant", "Alzheimer's", "Chickenpox", "Thighs", "Nasal spray",
  "Programmer", "Obese", "Herbal oil", "Red meat", "Calamine lotion", "Spotting", "Sitting down",
  "Journalist", "Concentrate", "Needles", "Cervical cancer", "Spirometry", "Steroids", "Excessive exercise", "Osteoarthritis", "Bruise", "Heel", "A translator", "Oil paints", "Atrial fibrillation", "Layout",
  "Heartbeats", "Clothes", "Broken ribs", "Rib cage", "Deep vein thrombosis", "Yoga",
  "Compartment syndrome", "Visual perception", "Vitamin D", "Gluten", "Japan", "Withdrawn",
  "Walking frame", "Ear infection", "Slurred", "Blurred", "Movement", "Climbing upstairs",
  "Commercial artist", "Heaviness", "Eczema", "Shingles", "Speaking", "Itchy", "Burning", "Calamine lotion", "Eczema", "Shingles", "Deodorant", "Shower gels", "Nasal spray", "Programmer", "Thighs",
  "Red meat", "Strength", "Intense", "Cycling", "Junk food", "Neighbour", "Incontinence", "Jaw", "Obese",
  "Slow", "Paralysis", "Wedding", "Watery", "Pleurisy", "Software developer", "Wisdom teeth",
  "Stroke", "Anxiety", "Sleep apnoea", "Beauty therapist", "Faint", "Cycling", "Stairs",
  "Psoriasis", "Stabbing", "Bronchitis", "Pleurisy", "Presentation", "Craft", "Fatigue", "Dyspepsia",
  "Engineer", "Seizures", "High-need baby", "Eyelids", "Vitamin B6", "Botox", "Rheumatic fever", "Twin sister", "Dental hygienist", "Tremor", "Cleft lip", "Grommet", "Mushroom", "Endometriosis",
  "Uncooperative", "Picky", "Behaviour", "Muscle tones", "Waking scheduled", "Judo",
  "Waved hand", "Arms", "Armpit", "Bipolar", "Sweat", "Shoulder", "Diarrhoea", "Epilepsy", "Biologist",
  "Depression", "Blister", "Hockey", "Taste", "Headache", "Floppy", "Elbow joint", "Both calves",
  "Backhand", "Ointment", "Systemic lupus", "Steroid", "Vertigo", "Juvenile rheumatoid arthritis",
  "Blindness", "Greasy", "Dandruff", "Warm compression", "Styes", "Tea tree oil", "Stinging",
  "Computer programmer", "Serious wrist fracture", "Dental assistant", "Osteoarthritis", "Sour",
  "Melatonin", "Astigmatism", "White", "Glue", "Oral / topical antibiotics", "Omega-3", "Mushrooms",
  "Choking", "Heartburn", "Rubella", "Salmonella", "Blinking", "Meniere's disease", "Lunch", "16mg",
  "Social gathering", "Tinnitus", "Stretching", "Acute inflammation", "Injections", "Bracing",
  "Shoulders", "Regurgitation", "Jogging", "Dog trainer", "Acoustic neuroma", "Whisper / whispering",
  "Stuttered", "Hammer", "Repeat", "Rheumatoid arthritis / fever", "Web designer", "Groin",
  "Echocardiogram", "Lupus", "Incontinence", "Constricted", "Hacking", "Asthma", "Pleurisy",
  "Repetitive nerve stimulation", "Drooping eyelid", "Prostate cancer", "Oat", "Heavy lifting",
  "Kidney stones", "Steroid tablet", "Right knee", "Plenty fluids", "Cholesterol", "Stomach cramps",
  "Wrist joint", "Slurred speech", "Chest infection", "Ventilator", "Flu vaccine", "Chewing", "Thymus gland", "Badminton sport", "Anxiety", "Double vision", "Achilles tendon", "Spitting", "Shoulder dystocia", "Preeclampsia", "Fever", "Knees", "Hips", "Nursery", "Tummy ache", "Chest X-ray", "Constipation", "Topical antibiotics", "Swollen", "Panic attack", "Dressing", "Pressure", "Two toes", "Temperature", "Tetanus vaccine", "Sepsis", "Financial difficulties", "Depression", "Deafness", "Awareness", "Brain fog", "Sharp brain", "Bereavement", "Surgery", "Arthritis", "Diabetes", "Vascular", "Angina", "Stroke", "Call centre", "Translator", "Left ventricle", "Obesity", "Blurred vision", "Stage 3", "Scuba diving", "Leukaemia", "Vascular dementia", "Convenient foods", "Swimming", "Voice", "Ears", "Sinuses", "Scoliosis", "Fertility", "Absence seizures", "Fractured rib", "Balance", "Convenience diet", "Stiff", "Weakness", "Energy", "Basketball", "Left thigh", "Longstanding", "Dark red", "Eczema", "Bandage", "Alcohol", "Hypertension", "Heavy", "Dairy", "Herbalist", "Pain", "Ice packs", "Pins and needles", "Stiffened",
  "Left ankle", "Poliovirus", "Hydrocortisone", "Standing up", "Smell", "Numbness", "Growing pains",
  "Cortisone cream", "Dairy products", "Weightlifting", "Dementia", "Left ventricular hypertrophy",
  "Absence seizure", "Convenience food", "Coughing fits", "Chest", "Canal", "Calves", "Thighs", "2 toes", "Warehouse", "Abdomen", "Piercing headache", "Fatigue", "Anaemia", "Leathery", "Botox",
  "Hip joint", "Wheezing", "Pus", "Blotchy", "Gout", "Beta blockers", "Rash", "Bold patch", "Ibuprofen",
  "Dengue fever", "Coordination", "Eyes", "Thyroid function", "Hormonal imbalance", "Anxiety attack", "Hotel receptionist", "Urinating", "Ferritin", "Epilepsy", "Collarbone", "Blue limbs", "Cracked lips", "Bloodshot", "Irritated", "Gout", "Carpenter", "Vibration", "Tingling", "Short of breath",
  "Acupuncture", "Accountant", "Hiking", "Cycling", "Peanut", "Underactive thyroid", "High-fibre diet", "Droopy", "Bloating", "Bladder", "Fitness", "Sciatica", "Pelvic congestion", "Appendicitis",
  "Fibre diet", "Antidepressant", "Kidney graft", "Embolisation", "Peanut allergy", "Hockey", "Security guard", "Both knees", "Ulcerative colitis", "Headaches", "Puberty", "Traffic noise", "Shellfish",
  "Floating", "Cheeks", "Web organiser", "Blood clots", "Lung cancer", "Colonoscopy", "Jaundice",
  "June", "Dark urine", "Prostatic cancer", "Insomnia", "Pacemaker", "Pulmonary embolism", "Itchy",
  "Saline drip", "Concussion", "Muscle", "Heparin injections", "Glandular fever", "Yoga", "Joint pain",
  "Skin rash", "Meningitis", "Ribs", "Driving instructor", "Vertigo", "Mini stroke", "Concentrate",
  "Kidney stone", "Housebound", "Groin area", "Scarlet fever", "Collarbone", "Blue limbs", "Cracked lips", "Bloodshot", "Irritated", "Gout", "Bilirubin", "Sticky eyes", "Booster injection", "Febrile convulsion", "Cirrhosis", "Dizziness", "Uncomfortable stomach", "Cataract", "Tea", "Ketogenic",
  "Right thumb", "Perfumed", "Hip replacement", "Alternative therapy", "Cold water", "Dry", "Flaky",
  "Blisters", "Awful", "Blood transfusion", "Throat infection", "Hydrated", "Bicycle", "Left thumb",
  "Flight attendant", "Beer", "Bearable", "Gluten", "Gluten-free diet", "Hydration", "Tonsillitis", "Tonsil", "Withdrawn", "Limping", "Upper limb", "Shoulder", "Knife", "Ankles", "Handwriting", "Healthy",
  "Gallstones", "Gallbladder", "Muscles", "Back", "Incontinence", "Sister", "Drive", "Aerobics", "Anaerobic", "Sugar", "Exam", "Sepsis", "Multiple system failure", "Peritonitis", "Right thumb",
  "Steroid", "Stomach pain", "Stomach ache", "Hernia", "Ventilation", "Colostomy", "Colonoscopy",
  "Stoma", "Cholesterol", "Multiple organ failure", "Menopause", "Growing pain", "Arthritis", "Flat mattress", "Coma", "Losing weight", "Abdominal pain", "Dark red urine", "Nosebleed", "Verapamil", "Vegetarian diet", "Vegetables", "Vegan", "Tooth extraction", "Cauterisation", "Cardiologist", "Cholecystectomy", "Golf ball", "Restless legs syndrome", "Scar", "Aspiration", "Burning", "Fish oil", "Zinc", "Humidity", "Stiffness", "Pregnancy", "Clicking", "Drill", "Mood swing", "Typically", "Constant pain", "Fracture", "Jewellery maker", "Carpal tunnel syndrome", "Burning sensation", "Nausea", "Gardener", "Floppy", "Tongue", "Earache", "Spasms", "Gums", "Exhaustion", "Breast cancer", "Femur", "Hay fever", "Project manager", "Patches", "Scarlet fever", "Antacid", "Craving", "Pus", "Hard", "Lighter", "Financial advisor", "Frontal lobe", "Seizure", "Meniere's disease",
  "Preventer", "Fuzzy", "Loss of hearing", "Social gathering", "Propranolol", "Tetanus", "Pancreatitis",
  "Antifungal", "Mechanic", "Vomiting", "Sinus infection", "Ladder", "Rotator cuff", "Co-codamol",
  "Tonic-clonic", "Complex partial", "VNS therapy", "Heparin injections", "Skin rashes", "Joint pain",
  "Concussions", "Anti-inflammatory", "Ethanol", "Fingers", "Freeze", "Joint pain", "Glaucoma", "Graphic designer", "Groggy", "Hearing loss", "Heat pads", "Heparin injection", "Herbal oil", "Impaction", "Injection", "Invasive", "Invitations", "Iron deficiency", "Japan", "Jobbing", "Jabbing", "Gapping", "Judge distance", "Kidney", "Layout", "Life-threatening", "Lifting", "Loss of energy", "Lunchtime", "Magazine editor", "Malaria", "Malaria tablets", "Meals", "Lunch", "Launch", "Mild fever", "Mouth ulcers", "Nail", "Nasal spray", "Nightmares", "Normal", "Off-colour", "Oil paint", "Opioid", "Optic disc", "Perception", "Pounding sound", "Pressure", "Prevention", "Psychological assessment", "Radiotherapy", "Red meat", "SLE (systemic lupus erythematosus)", "Salad", "Self-conscious", "Shadow", "Sharp brain", "Shooting", "Shower gels", "Skin rash", "Spots", "Steroid injections", "Superior aspect", "Temperature", "Tension headaches", "Tetanus vaccine", "Thyroid disease", "Toys", "Twisting", "Two toes", "Vascular", "Vertigo", "Vision", "Vitamin D", "Vocabulary", "Preventer", "Agitated", "Attack", "Autoimmune", "Bending over", "Bilirubin", "Bouncing sounds", "Brain scan", "Chubby", "Cleaner", "Clumps", "Concentration"
];

// Export the word list for use in other modules if needed
if (typeof module !== 'undefined' && module.exports) {
  module.exports = oetWordList;
}
